### ISSUE TITLE
Windows: Trailing path separators are removed

### ISSUE THREAD

**Issue by uklotzde** [rhysd/path-slash#10]
`to_slash()` behaves differently on Windows compared to other platforms. Trailing slashes in the result are removed even if the input ends with a path separator, i.e. `\`. Trailing path separators are preserved for Unix-like systems.

**Comment by uklotzde** [comment]
Thank you!

**Comment by rhysd** [comment]
Since this is a breaking change, it will be included in next release v0.2.0.

**Comment by rhysd** [comment]
This change is included in the new release [v0.2.0](https://github.com/rhysd/path-slash/releases/tag/v0.2.0).
