### ISSUE TITLE
C://Windows -> really?

### ISSUE THREAD

**Issue by jeanga** [rhysd/path-slash#3]
Hi,

I find path-slash really interesting but I cannot understand the rationale between this behavior:

Why insist on doubling \\ (or //) rigth after the driver specification (i.e. as in C:\\Windows)?
I have been working on Windows for 25 years and I _never_ saw this syntax.

Is there any reason behind this choice of implementation?

Thanks for the otherwise great crate!
Jean

**Comment by rhysd** [comment]
Thanks. It was just a mistake in docs and tests. Fixed in 7e68ded

**Comment by jeanga** [comment]
Thank you!
