### ISSUE TITLE
On Linux, no Windows path to Linux?

### ISSUE THREAD

**Issue by picobyte** [rhysd/path-slash#7]
On my Linux I cannot seem to convert a Windows path to a Linux path via path-slash, why is this not supported? I have a use-case where this make sense, trying to concatenate a relative path usually specified in windows path format, to a Linux root path.

```rust
use path_slash::PathExt;
use std::path::Path;

fn main() {
    let pre = r"FOMod\CBBE.png";
    println!("{}", pre);

    let path = Path::new(pre);
    println!("1: {}", path.display());

    // suggested in the docs, but does not work either:
    println!("2: {}", PathBuf::from(pre).display());
    let supposedly_slashed = path.to_slash().unwrap();

    println!("3: {}", supposedly_slashed);

    let works = path::PathBuf::from_backslash(pre);
    println!("4: {}", works.display());
}
```
output (no. 4 works, but only after my pull request)
```
FOMod\CBBE.png
1: FOMod\CBBE.png
2: FOMod\CBBE.png
3: FOMod\CBBE.png
4: FOMod/CBBE.png
```
Then aren't the crate and function misnomers? Path-backslash, and to_backslash() would indicate what to expect.
```
Linux 5.12.15-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux
rustc 1.55.0-nightly (3e1c75c6e 2021-07-13)
path-slash = "0.1.4"
```

on Linux it is possible to create a directory with a backslash `mkdir "foo\\bar"` so maybe some behavior in PathBuf was adapted. I've added a pull request #8 to add from_backslash() functions, which should hopefully do the job.

**Comment by rhysd** [comment]
This was fixed by #8. Closing.
